/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesNuevoRouteImport } from './routes/quizzes/nuevo'
import { Route as QuizzesIdRouteImport } from './routes/quizzes/$id'
import { Route as QSlugRouteImport } from './routes/q/$slug'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesNuevoRoute = QuizzesNuevoRouteImport.update({
  id: '/quizzes/nuevo',
  path: '/quizzes/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIdRoute = QuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QSlugRoute = QSlugRouteImport.update({
  id: '/q/$slug',
  path: '/q/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/q/$slug': typeof QSlugRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/quizzes/nuevo': typeof QuizzesNuevoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/q/$slug': typeof QSlugRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/quizzes/nuevo': typeof QuizzesNuevoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/q/$slug': typeof QSlugRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/quizzes/nuevo': typeof QuizzesNuevoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/registro'
    | '/q/$slug'
    | '/quizzes/$id'
    | '/quizzes/nuevo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/registro'
    | '/q/$slug'
    | '/quizzes/$id'
    | '/quizzes/nuevo'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/registro'
    | '/q/$slug'
    | '/quizzes/$id'
    | '/quizzes/nuevo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  QSlugRoute: typeof QSlugRoute
  QuizzesIdRoute: typeof QuizzesIdRoute
  QuizzesNuevoRoute: typeof QuizzesNuevoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/nuevo': {
      id: '/quizzes/nuevo'
      path: '/quizzes/nuevo'
      fullPath: '/quizzes/nuevo'
      preLoaderRoute: typeof QuizzesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$id': {
      id: '/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof QuizzesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$slug': {
      id: '/q/$slug'
      path: '/q/$slug'
      fullPath: '/q/$slug'
      preLoaderRoute: typeof QSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  QSlugRoute: QSlugRoute,
  QuizzesIdRoute: QuizzesIdRoute,
  QuizzesNuevoRoute: QuizzesNuevoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
